### ISSUE TITLE
Question: What are the statuses of vendor prefixed properties?

### ISSUE THREAD

**Issue by kt3k** [WICG/entries-api#42]
The spec includes a few vendor prefixed properties and functions (`webkitRelativePath`, `webkitdirectory`, `webkitEntries`, and `webkitGetAsEntry`). Are those intended to be standardized as is?

**Comment by inexorabletash** [comment]
Per https://wpt.fyi/results/entries-api/idlharness.window.html?label=experimental&label=master&aligned

Chromium (Chrome, Edge), Gecko (Firefox) and WebKit (Safari) all have:
* File interface: attribute webkitRelativePath
* HTMLInputElement interface: attribute webkitdirectory	
* HTMLInputElement interface: attribute webkitEntries	
* DataTransferItem interface: operation webkitGetAsEntry()	

(FYI, the failures are because Chromium ran into compat issues trying to rename `Entry` to `FileSystemEntry` etc and pushing to align has been very low priority for a long time.)

This document specifies a "de facto standard", i.e. it describes the reality of things. So by that metric, yes they are standardized. Does everyone involved wish this whole API didn't exist and was replaced by something with better performance and ergonomics? Also yes.
