### ISSUE TITLE
Consider renaming Entry to something else

### ISSUE THREAD

**Issue by domenic** [WICG/entries-api#6]
E.g. FileOrDirectoryEntry. See [blink-dev concerns about the name in global scope](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/_6Euwqv366U)

**Comment by inexorabletash** [comment]
Aside: rename DOMFileSystem to something less grotesque at the same time? I dunno..

**Comment by inexorabletash** [comment]
... and then drop `[NoInterfaceObject]` on the types, per [inline issue](https://wicg.github.io/entries-api/#issue-15e296d3)

I'm really hoping to avoid Edge's `webkitFileEntry` and friends getting baked into the platform, but is there a chance Edge and Gecko will follow suit if Chrome makes this change?

@aliams @smaug---- ?

**Comment by smaug----** [comment]
FileSystemEntry perhaps? and then drop NoInterfaceObject

**Comment by aliams** [comment]
I think it's low enough risk to change the names of these interfaces in Edge since they are NoInterfaceObjects in Chrome and Firefox and hence never actually referenced by a web developer in their code.

How do you feel about prefixing these interfaces with something like `FileSystem`:

- `FileSystem`
- `FileSystemEntry`
- `FileSystemFileEntry`
- `FileSystemDirectoryEntry`

Alternatively, we can prefix with `FS` so the interface names aren't as lengthy.

On the other hand, would you prefer that we only change `Entry` to avoid it's ambiguity as per the blink-dev thread?

**Comment by smaug----** [comment]
FileSystem prefix with them all sounds good.

**Comment by inexorabletash** [comment]
HTTPArchive (2016-08-01) turns up:

* 0 hits on `FileSystemEntry`
* 0 hits on `FileSystemFileEntry`
* 0 hits on `FileSystemDirectoryEntry`

.. so I think we're good there!

`FileSystem` itself has a couple hits as `window.FileSystem` and `var FileSystem` (searching for "FileSystem" on its own gets hundreds of hits, since it's such a generic phrase, so I'm ignoring that)

* [One use](https://github.com/apache/cordova-plugin-file/blob/master/www/FileSystem.js) of `var FileSystem = ...` -this would overwrite the new global and keep working.
* [One use](https://app.contentdirect.tv/Storefront/HTML/v5.6.1.19/Scripts/contentdirect.ui.common.js) of `"undefined"!=typeof window.FileSystem` as part of a long browser detection scheme (looking for Samsung SmartHub devices); the first part of the test does a string test for a proprietary OS and later look for specific firmware.

Should we ahead with trying `DOMFileSystem` &rarr; `FileSystem` or just keep that one? (there were 0 hits for `window.DOMFileSystem` and `var DOMFileSystem`). Other phrases I should search on?

**Comment by annevk** [comment]
Not having `DOM`-prefixes would be nice. I like @aliams' list.

**Comment by smaug----** [comment]
@inexorabletash so which naming will blink use? 
Especially FileSystem or DOMFileSystem?


@bakulf ^

**Comment by annevk** [comment]
@smaug---- see https://groups.google.com/a/chromium.org/d/msg/blink-dev/xTfeHGlcIQg/X0Q4iDJHAgAJ. The intent specifies FileSystem, but it's not yet approved or tried.

**Comment by bakulf** [comment]
We should rename DirectoryReader to FileSystemDirectoryReader as well.

**Comment by bakulf** [comment]
I suggest to rename these callbacks too:

BlobCallback -> FileSystemBlobCallback
EntriesCallback -> FileSystemEntriesCallback
EntryCallback -> FileSystemEntryCallback
ErrorCallback -> FileSystemErrorCallback
VoidCallback -> FileSystemVoidCallback

**Comment by smaug----** [comment]
Yeah, I think those changes make sense and keep the API more consistent. And the tiny bit long names don't really matter in practice.

**Comment by annevk** [comment]
Is BlobCallback not in HTML already?

**Comment by annevk** [comment]
(Callback names are not exposed by the way so their names matter much less, if at all.)

**Comment by bakulf** [comment]
FileCallback is part of HTMLCanvasElement. BlobCallback doesn't exist yet.
Probably it's OK to keep BlobCallback, ErrorCallback and VoidCallback. But EntriesCallback and EntryCallback should follow the new names.

**Comment by inexorabletash** [comment]
Change was approved for Blink. I'm travelling so it'll be a couple days before I can make the change and update the spec.

I agree with @bakulf's last comment, and will rename the FileSystemEntry/Entries callbacks as well for spec consistency in case plain "Entry" does make it into another spec in the future.

**Comment by inexorabletash** [comment]
I don't suppose anyone wants to review https://github.com/WICG/entries-api/pull/8 ?

**Comment by smaug----** [comment]
@bakulf could you check if ^ matches your patch, in other words review the change here.

**Comment by inexorabletash** [comment]
Note that it may take some time for Blink to make the change since there are lots of internal dependencies c/o the use of the same types for the Chrome-only FileSystem API. Worst case we can "fork" our impl for the Directory Upload use case vs. File System case. But that's an impl issue, so resolving here.

**Comment by bakulf** [comment]
@smaug---- , yes this is what we have in gecko.
